name: Ephemeral Environment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3.5.0
      with:
        node-version-file: pulumi/package.json

    - name: Install Dependencies
      working-directory: pulumi
      run: npm install

    - name: Install Pulumi CLI
      uses: pulumi/actions-install-pulumi-cli@v1.0.1

    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}