name: Ephemeral Environment
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3.5.0
      with:
        node-version: 18
        
    - name: Get cache key for Node.js modules
      id: cache
      run: echo "::set-output name=key::$(date +'%Y-%m-%d')-$(hashFiles('pulumi/package-lock.json'))"

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: pulumi/node_modules
        key: ${{ runner.os }}-node-${{ steps.cache.outputs.key }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      working-directory: pulumi
      run: npm install

    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: bryan-rhm/yugalabs/dev
        work-dir: pulumi
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}